### ISSUE TITLE
Qt6 적용 후 동작 안댑니다

### ISSUE THREAD

**Issue by gguram** [C4NU/WebP-Converter-GUI#24]
아래 버튼 눌렀을때 멎는거는 checked부분 코드 Qt6에 맞춰주면 되는데, 
세이브 누르면 팅겨버림 

해결해줘 도라에몽
그전버전으로 기능만 치고있을게

**Comment by komastar** [comment]
ㅇㅋ

**Comment by C4NU** [comment]
이슈 이후로 수정되엇나여

맥에서 pyqt6 패키지로 갈아타고 pull 해서 테스트 해봣는데 잘돌아가여

**Comment by gguram** [comment]
헉 저 윈도우인데 안돌던데 뭐가문제지

**Comment by gguram** [comment]
어?? 왜 잘돌지????

**Comment by gguram** [comment]
뭐야 그럼 빌드해줘요!

**Comment by komastar** [comment]
ㅇㅅㅇ?

**Comment by gguram** [comment]
진짜 몰름,,, 분명 안됫는데,,, 고친것도 없을텐데,,,
