### ISSUE TITLE
[Build] Segmantation Fault

### ISSUE THREAD

**Issue by C4NU** [C4NU/WebP-Converter-GUI#27]
메모리 접근 관련 오류일텐데

쉬발 뭐지 빌드할때만 그런데

**Comment by komastar** [comment]
Log

**Comment by C4NU** [comment]
print(os.system("python3 --version"))
    import app_window -> main에서 실행하고 
    
    app_window 호출할때 segmantation 에러가 뜨는거같아여

user_data json 읽어올때 문제인가......

**Comment by C4NU** [comment]
User_config 에서 pyqt6 패키지 위에 불러올때 뻑나는거 보니 제가 따로 빌드할 때 패키지 설정만 다시해주면 정상적으로 돌아가지 않을...까 싶네여 호호호홍

**Comment by C4NU** [comment]
히히 윈도우는 빌드 잘댄다

**Comment by C4NU** [comment]
macOS 해결

from PyQt6 import QtGui
from PyQt6.QtGui import QColor

PyQt6를 단계적으로 import 하면 해결?

혹은 Pyinstaller과 macOS의 PyQt6 패키지가 서로 호환성이 안좋은지 뭐..아무튼...

https://github.com/pyinstaller/pyinstaller/issues/7789

이거 같이 참조하면 해?결 되네여
