### ISSUE TITLE
[폰트 미리보기] 특정 폰트 선택시 Italic 적용 안되는 문제

### ISSUE THREAD

**Issue by C4NU** [C4NU/WebP-Converter-GUI#29]
Barlow-Black 설정 후
Barlow-BlackItalic 설정하면 Italic 채가 미리보기에서 적용이 안되는데

다른 Italic 옵션도 적용이 안대네영

![image](https://github.com/C4NU/WebP-Converter-GUI/assets/9432240/378cd402-9dbe-49b6-a23a-477b2009e27a)

**Comment by komastar** [comment]
https://github.com/C4NU/WebP-Converter-GUI/pull/31

**Comment by C4NU** [comment]
앗 resize ui 파일이 업따

**Comment by komastar** [comment]
아 누락이네 집 가면 올림

**Comment by komastar** [comment]
완료
