### ISSUE TITLE
이슈는 아니지만 UI 제안

### ISSUE THREAD

**Issue by gguram** [C4NU/WebP-Converter-GUI#32]
![UIExample](https://github.com/C4NU/WebP-Converter-GUI/assets/144647922/dc9a8e98-06f9-40a5-8ca1-d08c9e47a0de)

결과물 미리보기 간단하게 만들어주면 좀 괜찮을거같은데
좌측에 넓게 옵션창 가져가면 옵션창 굳이 분리할 필요도 없을 것 같고 
몰?루

**Comment by komastar** [comment]
그럼 선행해야 하는 작업은 리팩토링

UI 클래스 분리
- 옵션과 기능에 따라 클래스로 따야함

UI 앵커/레이아웃
- 스택 레이아웃 같은걸 써서 UI가 정렬되어서 들어가도록 해야함

클래스들 분리와 함께 모듈들을 적절한 위치로 옮겨야함

**Comment by gguram** [comment]
일단 기능들 위주로 다 때려넣다가 추가할 기능 없을때 2버전쯤에 UI 격변 몰아다가 한번에 할까요?
계속 뭐 추가될거 같은데.

그냥 지금 상태에서 레이아웃만 바꾸고 미리보기창+균일한 레이아웃 썸네일 창만 추가하면 될거같았는데

**Comment by komastar** [comment]
지금정도 사이즈에서 쉽게 정리 가능해서
적당히라도 정리해둬야 나중에 피를 덜 보고
컨플릭트도 줄이는 길
프로젝트 오너가 판단하죠

**Comment by gguram** [comment]
운전대 잡은자 그 무게를 견뎌라

**Comment by gguram** [comment]
글고 지금 conversion 옵션이랑 EXIF 옵션 상충되는데, 
사실 병행되도 되지 않나요? <- 진짜 몰라서 궁금함

**Comment by komastar** [comment]
저 둘을 구분하는 분석은 따로 안해서 저도 모름..

**Comment by C4NU** [comment]
![image](https://github.com/C4NU/WebP-Converter-GUI/assets/9432240/c6a0675d-4ea6-423e-a037-43eeac4cda3f)

이런 스타일로 아예 UI 바꿀 예?정 인데 결국 함 뜯어내는게 좋겟져?


그 변환 옵션이랑 exif 레터박스 이미지랑 옵션 혼용 안되게 햐놓은것두 저렇게 옵션으로 뜯어낼라고 막아놧써여

**Comment by gguram** [comment]
![DemoScreen_main](https://github.com/C4NU/WebP-Converter-GUI/assets/144647922/d8ed714a-e7f1-463b-b87c-3bf27219340e)
![DemoScreen_option](https://github.com/C4NU/WebP-Converter-GUI/assets/144647922/abdaf484-3e46-40de-9440-8322519becf2)
청춘돼지는 QML로 APP까지의 미래를 꿈꾼다

**Comment by C4NU** [comment]
Kivy였나 그거로 옮기면 app까지 다 된다고 하는데 뭔가 땡기다가도 지금 mac 빌드 시발시발하는거 생각하면 또 골치아프고 그럽디다

**Comment by gguram** [comment]
저렇게 나누면 컨버팅만 하고싶으면 
BG랑 Text option 아무것도 체크안하고 Export하고 
Exif 넣은다음에 WebP 변환까지 하고싶으면 체크하면 되자너

**Comment by C4NU** [comment]
아예 webP 변환 / Exif 변환 합치는것도 좋은 옵션이긴 한데 그렇게 되면 프로그램 사용이 너무 복잡해지지 않을지 걱정

**Comment by gguram** [comment]
심플모드 / 디테일 모드로 나누는 것도 괜찮을거 같음
심플에서는 고정된 몇개 옵션 세팅만 내놓고, 디테일 모드에서는 혼용사용하게 하고

단순 제안이고 언제나 선장은 선생님입니다 충성충성
<img width="708" alt="simpe_advance" src="https://github.com/C4NU/WebP-Converter-GUI/assets/144647922/c57acd6e-0941-4e69-a3a4-afeac870ba4b">

**Comment by komastar** [comment]
UI 관련 코드 작업 필요한거 있음?

**Comment by C4NU** [comment]
https://github.com/C4NU/WebP-Converter-GUI/issues/4#issuecomment-1731112838

요런식으로 지금 작업하고잇는데

아직 webp_module 쪽에 각각 option 윈도우의 데이터를 링킹하는걸 테스트하는중이라 잘 몰루겟어요
