### ISSUE TITLE
파노라마 사진 넣으면 에러남

### ISSUE THREAD

**Issue by vkdl142857** [C4NU/WebP-Converter-GUI#36]
제곧내

https://photos.app.goo.gl/pNHbBdwoHYideGBJ8

위 링크에 있는 사진으로 넣었는데 안만들어지고 꺼짐
jpeg 만들 때 일부러 장축 줄여서 넣어도 그럼

**Comment by C4NU** [comment]
테스트 해보겟읍니다

**Comment by C4NU** [comment]
exif - padding 변환인가여

아니묜 webp 변환인가여

![2J1A6840-Pano 복사](https://github.com/C4NU/WebP-Converter-GUI/assets/9432240/3377814e-5a2c-4386-9853-a8e83c4959f0)

exif 데이터가 업어서 일케 나오긴 하는뎅

**Comment by vkdl142857** [comment]
> exif - padding 변환인가여
> 
> 아니묜 webp 변환인가여
> 
> ![2J1A6840-Pano 복사](https://user-images.githubusercontent.com/9432240/268557124-3377814e-5a2c-4386-9853-a8e83c4959f0.jpeg)
> 
> exif 데이터가 업어서 일케 나오긴 하는뎅

![image](https://github.com/C4NU/WebP-Converter-GUI/assets/145269687/750ab9ba-24ee-44e5-8bfa-80e92787f46a)

일케하고 올렸어요

**Comment by vkdl142857** [comment]
윈도우10에서 하고 있는데 여전히 안되요
그리고 용량 큰 거는 사진 여러장 찍어서 파노라마 합성해서 그래요

**Comment by vkdl142857** [comment]
![image](https://github.com/C4NU/WebP-Converter-GUI/assets/145269687/f17d727c-db07-4783-a864-a3a44f4b1dc3)

이유 알아냈음!
웹피 패딩으로 파노라마 사진 변환하면 걍 꺼짐!
동일 조건으로 jpg하면 멀쩡하게 나와요

**Comment by C4NU** [comment]
Webp only allows up to 16,383 x 16,383 pixels.

WebP 이미지는 최대 16383 * 16383 사이즈까지만 지원해서 이거는 기술적 문제로 해결이 불가능하대용
